services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: fm-web-dev
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - ALLOWED_USERNAMES=auto7313
    volumes:
      - ./web/src:/app/src
    networks:
      - fm-net

  bot:
    build:
      context: ./main-bot
      dockerfile: Dockerfile
    container_name: fm-bot-dev
    restart: always
    environment:
      - ENVIRONMENT=development
      - ALLOWED_USERNAMES=auto7313
    volumes:
      - ./main-bot/src:/app/src
    networks:
      - fm-net

networks:
  fm-net:
    driver: bridge
