services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fm-bot
    restart: always
    environment:
      - ENVIRONMENT=development
      - ALLOWED_USERNAMES=auto7313
    volumes:
      - ./src:/app/src
