-- FoodMaster operational PostgreSQL schema.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS schema_migrations (version varchar(100) PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS merchants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(255) NOT NULL UNIQUE, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS portals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id uuid NOT NULL REFERENCES merchants(id), name varchar(255) NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (merchant_id, name));
CREATE TABLE IF NOT EXISTS shopee_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), portal_id uuid NOT NULL REFERENCES portals(id), merchant_id_external varchar(100) NOT NULL DEFAULT '', username varchar(255) NOT NULL, phone varchar(50), password_plain text, session_file text, is_active boolean NOT NULL DEFAULT true, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (portal_id, username));
CREATE TABLE IF NOT EXISTS dashboard_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id uuid REFERENCES merchants(id), username varchar(255) NOT NULL UNIQUE, password_plain text NOT NULL DEFAULT 'Master@123', link_slug varchar(255) UNIQUE, dashboard_url text, role varchar(20) NOT NULL DEFAULT 'MERCHANT', is_active boolean NOT NULL DEFAULT true, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO dashboard_accounts (username,password_plain,role,is_active) VALUES ('admin','Admin@123','ADMIN',true) ON CONFLICT (username) DO NOTHING;
CREATE TABLE IF NOT EXISTS bot_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username varchar(255) NOT NULL UNIQUE, password_plain text NOT NULL, name varchar(255) NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bot_merchant_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bot_account_id uuid NOT NULL REFERENCES bot_accounts(id) ON DELETE CASCADE, merchant_id uuid NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, is_active boolean NOT NULL DEFAULT true, assigned_at timestamptz NOT NULL DEFAULT now(), UNIQUE (bot_account_id, merchant_id));
CREATE TABLE IF NOT EXISTS outlets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id uuid NOT NULL REFERENCES merchants(id), portal_id uuid NOT NULL REFERENCES portals(id), shopee_account_id uuid REFERENCES shopee_accounts(id), store_id varchar(100) NOT NULL UNIQUE, ownership_type varchar(100), long_name varchar(255) NOT NULL, special_hours text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS outlet_states (outlet_id uuid PRIMARY KEY REFERENCES outlets(id) ON DELETE CASCADE, vercel_status varchar(10) NOT NULL DEFAULT 'OFF' CHECK (vercel_status IN ('ON','OFF')), shopee_actual_status varchar(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (shopee_actual_status IN ('ON','PAUSE','OFF','UNKNOWN')), suspension_status varchar(20) NOT NULL DEFAULT 'ACTIVE' CHECK (suspension_status IN ('ACTIVE','SUSPENDED')), suspension_reason text, suspended_at timestamptz, suspension_ends_at timestamptz, pause_until timestamptz, last_checked_at timestamptz, last_action_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS operating_hours (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outlet_id uuid NOT NULL REFERENCES outlets(id) ON DELETE CASCADE, weekday smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6), open_time time, close_time time, is_closed boolean NOT NULL DEFAULT false, UNIQUE (outlet_id, weekday));
CREATE TABLE IF NOT EXISTS subscription_plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code varchar(30) NOT NULL UNIQUE, name varchar(100) NOT NULL, base_months smallint NOT NULL DEFAULT 3, bonus_months smallint NOT NULL DEFAULT 0, total_months smallint GENERATED ALWAYS AS (base_months + bonus_months) STORED, price numeric(12,2) NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outlet_id uuid NOT NULL REFERENCES outlets(id), plan_id uuid NOT NULL REFERENCES subscription_plans(id), start_date date NOT NULL, end_date date NOT NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', amount numeric(12,2), payment_reference varchar(255), created_by uuid REFERENCES dashboard_accounts(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK (end_date >= start_date));
CREATE TABLE IF NOT EXISTS automation_logs (id bigserial PRIMARY KEY, outlet_id uuid REFERENCES outlets(id), checked_at timestamptz NOT NULL DEFAULT now(), suspension_status varchar(20) NOT NULL DEFAULT 'ACTIVE', subscription_status varchar(20) NOT NULL DEFAULT 'ACTIVE', vercel_status_before varchar(10) NOT NULL DEFAULT 'OFF', shopee_status_before varchar(20) NOT NULL DEFAULT 'UNKNOWN', target_status varchar(20) NOT NULL, action varchar(40) NOT NULL, shopee_status_after varchar(20), success boolean NOT NULL DEFAULT false, error_message text, reason text);
CREATE TABLE IF NOT EXISTS admin_audit_logs (id bigserial PRIMARY KEY, admin_account_id uuid REFERENCES dashboard_accounts(id), outlet_id uuid REFERENCES outlets(id), action varchar(80) NOT NULL, old_value jsonb, new_value jsonb, reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS outlets_merchant_idx ON outlets (merchant_id);
CREATE INDEX IF NOT EXISTS outlets_portal_idx ON outlets (portal_id);
CREATE INDEX IF NOT EXISTS subscriptions_outlet_end_idx ON subscriptions (outlet_id, end_date DESC);
CREATE INDEX IF NOT EXISTS automation_logs_outlet_checked_idx ON automation_logs (outlet_id, checked_at DESC);
INSERT INTO subscription_plans (code,name,base_months,bonus_months,price) VALUES ('3_MONTHS','Paket 3 Bulan',3,0,90000),('6_MONTHS','Paket 6 Bulan',6,1,180000),('12_MONTHS','Paket 12 Bulan',12,4,360000) ON CONFLICT (code) DO NOTHING;
INSERT INTO schema_migrations (version) VALUES ('001_initial_schema') ON CONFLICT (version) DO NOTHING;
